# Generated by Django 5.1.1 on 2024-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('barcode', models.CharField(blank=True, max_length=10, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
    ]
